### PR TITLE
Pr 11 Suggestions

### PR DESCRIPTION
**Pull request by eralpkaraduman**
Hey @hungneox here are my suggestions based on your [PR](https://github.com/eralpkaraduman/event_dot_pizza/pull/22) about adding today tab.

Basically;
- Refactored the provider integration
- Refactored bottom nav bar implementation (made compositional)
  - Also renamed All -> Anytime (imo communicates bit more clearly)
  - Changed icon for anytime
- The main thing: Each tab has a separate list view widget so their states are kept separately
  - Implementation is based on IndexedStack so only one of them is visible at a time.
  - Wrapped listviews with Scrollbar widgets so they render the scroll indicators
  - Removed scrollphysics param so flutter could pick depending on the platform
    - Otherwise alwaysscroll feels bit weird on android

What do you think?

### CODE REVIEW

**Comment by q-hung** [comment]
Cool! I will try this out. This looks so clean.

**Comment by q-hung** [comment]
If I understand correctly this use `IndexedStack`, and it will allows us to have 2 ListView at the same time, so there is no animation when changing tab.

**Comment by q-hung** [comment]
LGTM

**Review by q-hung — APPROVED** [review]
Thanks!!!

**Comment by eralpkaraduman** [comment]
> If I understand correctly this use `IndexedStack`, and it will allows us to have 2 ListView at the same time, so there is no animation when changing tab.

Exactly.
That animation was a side effect of swapping so much items in a list probably.

I thank you back, sir. 👍

**Pull request merged**
